apiVersion: v1
kind: Service
metadata:
  name: frontend-server-service
  labels:
    app: messenger.frontend-server
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
  selector:
    app: messenger.frontend-server
